# Generated by Django 4.2.9 on 2024-07-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersonalreagent',
            name='laboratory',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personalreagent',
            name='laboratory',
            field=models.CharField(max_length=20),
        ),
    ]
