# Generated by Django 4.2.9 on 2024-09-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_laboratory_historicallaboratory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazardstatement',
            name='clp_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reagents.clpclassification'),
        ),
    ]
