# Generated by Django 4.2.9 on 2024-09-30 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reagents.validators
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0003_alter_hazardstatement_clp_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyDataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_data_sheet', models.FileField(upload_to='SafetyDataSheets')),
                ('name', models.CharField(max_length=7, validators=[reagents.validators.SafetyDataSheetNameValidator()])),
                ('reagent_name', models.CharField(max_length=100)),
                ('is_validated_by_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'reagents_safety_data_sheet',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SafetyInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_instruction', models.FileField(upload_to='SafetyInstructions')),
                ('name', models.CharField(max_length=6, validators=[reagents.validators.SafetyInstructionNameValidator()])),
                ('reagent_name', models.CharField(max_length=100)),
                ('is_validated_by_admin', models.BooleanField()),
            ],
            options={
                'db_table': 'reagents_safety_instruction',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalreagent',
            name='safety_data_sheet_name',
        ),
        migrations.RemoveField(
            model_name='historicalreagent',
            name='safety_instruction_name',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='safety_data_sheet_name',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='safety_instruction_name',
        ),
        migrations.CreateModel(
            name='HistoricalSafetyInstruction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('safety_instruction', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=6, validators=[reagents.validators.SafetyInstructionNameValidator()])),
                ('reagent_name', models.CharField(max_length=100)),
                ('is_validated_by_admin', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical safety instruction',
                'verbose_name_plural': 'historical safety instructions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSafetyDataSheet',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('safety_data_sheet', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=7, validators=[reagents.validators.SafetyDataSheetNameValidator()])),
                ('reagent_name', models.CharField(max_length=100)),
                ('is_validated_by_admin', models.BooleanField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical safety data sheet',
                'verbose_name_plural': 'historical safety data sheets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name='historicalreagent',
            name='safety_data_sheet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reagents.safetydatasheet'),
        ),
        migrations.AlterField(
            model_name='historicalreagent',
            name='safety_instruction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reagents.safetyinstruction'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='safety_data_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reagents.safetydatasheet'),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='safety_instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reagents.safetyinstruction'),
        ),
    ]
