# Generated by Django 4.2.9 on 2024-09-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0004_safetydatasheet_safetyinstruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpersonalreagent',
            name='opening_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='personalreagent',
            name='opening_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
